name: Update README with Recent Commit SVG

on:
 schedule:
    - cron: '*/5 * * * *'
 workflow_dispatch:

env:
  USER: ${{ secrets.USER }}

jobs:
 update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Update README
      run: node update-readme.js

    - name: Commit and push if it changed
      run: bash update-git.sh
