name: Update README with Recent Commit SVG

on:
 schedule:
    - cron: '*/5 * * * *'
 workflow_dispatch:

env:
  USER: ${{ secrets.USER }}

jobs:
 update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Generate SVG
      run: node generate-svg.js

    - name: Commit and push if it changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add README.md recent-commit.svg
        git diff --quiet && git diff --staged --quiet || git commit -m "Update README with recent commit SVG"
        git push
